#!/usr/bin/env node
/**
 * Generates plugin/hooks/lib/version.mjs from package.json.
 *
 * The hook runtime is plain ESM that ships alongside (not through) the
 * TypeScript build, so it cannot import package.json the way src/ does. Before
 * v0.7.0 the version was hand-copied into three places and drifted silently.
 *
 * Wired into `npm run build` rather than a prepack/prepare hook: the documented
 * install path is a git clone + `npm run build` + `npm link`, and prepack never
 * runs there.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));

const out = `// GENERATED by scripts/generate-version.mjs — do not edit.
// Source of truth is package.json "version". Regenerate with \`npm run build\`.
export const COLLECTOR_VERSION = '${version}';
`;

writeFileSync(join(root, 'plugin', 'hooks', 'lib', 'version.mjs'), out, 'utf-8');

// The CLI can't `import pkg from "../../package.json"`: package.json sits
// outside rootDir, which breaks the emitted directory layout. Generate a
// sibling .ts instead so both runtimes read the same single source of truth.
const outTs = `// GENERATED by scripts/generate-version.mjs — do not edit.
// Source of truth is package.json "version". Regenerate with \`npm run build\`.
export const COLLECTOR_VERSION = "${version}";
`;
writeFileSync(join(root, 'src', 'core', 'version.ts'), outTs, 'utf-8');
process.stdout.write(`generate-version: COLLECTOR_VERSION=${version}\n`);
